spring:
  application:
    name: TrocAppBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/TrocApp  # Nom de ta base de données
    username: postgres  # Utilisateur PostgreSQL
    password: main01  # Mot de passe PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  #Dialecte PostgreSQL pour Hibernate

jwt:
  secret: fjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvxfjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvx
  expirationTokenMs: 3600000
  expirationRefreshTokenMs: 604800000