spring:
  application:
    name: TrocAppBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/TrocApp  # Nom de ta base de données
    username: postgres  # Utilisateur PostgreSQL
    password: main01  # Mot de passe PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update # Création de la base de données
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect  #Dialecte PostgreSQL pour Hibernate
